// Generated by Swift version 1.1 (swift-600.0.56.1)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if defined(__has_include) && __has_include(<uchar.h>)
# include <uchar.h>
#elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
#endif

typedef struct _NSZone NSZone;

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted) 
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if defined(__has_feature) && __has_feature(modules)
@import ObjectiveC;
#endif

#import <SimpleMQTTClient/SimpleMQTTClient.h>

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
@class MQTTSession;
@class NSData;
@class NSError;
@protocol SimpleMQTTClientDelegate;

SWIFT_CLASS("_TtC16SimpleMQTTClient16SimpleMQTTClient")
@interface SimpleMQTTClient : NSObject <MQTTSessionDelegate>
@property (nonatomic) BOOL synchronous;
@property (nonatomic, weak) id <SimpleMQTTClientDelegate> delegate;
- (instancetype)initWithSynchronous:(BOOL)synchronous clientId:(NSString *)optionalClientId OBJC_DESIGNATED_INITIALIZER;
- (instancetype)initWithHost:(NSString *)host synchronous:(BOOL)synchronous clientId:(NSString *)optionalClientId;
- (void)subscribe:(NSString *)channel;
- (void)unsubscribe:(NSString *)channel;
- (NSArray *)getSubscribedChannels;
- (BOOL)isSubscribed:(NSString *)channel;
- (void)publish:(NSString *)channel message:(NSString *)message;
- (void)disconnect;
- (void)connect:(NSString *)host;
- (void)newMessage:(MQTTSession *)session data:(NSData *)data onTopic:(NSString *)topic qos:(MQTTQosLevel)qos retained:(BOOL)retained mid:(uint32_t)mid;
- (void)handleEvent:(MQTTSession *)session event:(MQTTSessionEvent)eventCode error:(NSError *)error;
- (void)subAckReceived:(MQTTSession *)session msgID:(uint16_t)msgID grantedQoss:(NSArray *)grantedQoss;
- (void)unsubAckReceived:(MQTTSession *)session msgID:(uint16_t)msgID grantedQoss:(NSArray *)grantedQoss;
@end


SWIFT_PROTOCOL("_TtP16SimpleMQTTClient24SimpleMQTTClientDelegate_")
@protocol SimpleMQTTClientDelegate
@optional
- (void)messageReceived:(NSString *)channel message:(NSString *)message;
- (void)disconnected;
- (void)connected;
@end

#pragma clang diagnostic pop
